name: "Label Messager"
description: "Automatically leave a message when an issue or pull request has a certain label"
inputs:
  repo-token:
    description: "GITHUB_TOKEN secret"
    required: true
  message-directory:
    description: "The directory path containing all of the messages"
    default: ".github/label-messager"
  operations-per-run:
    description: "The rough number of github API calls to do per background run. This is to avoid running up against rate limits."
    default: 50
runs:
  using: 'node12'
  main: 'dist/index.js'
